improve final check conditions

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -92,16 +92,31 @@ jobs:
         run: |
           pre_merge_pipeline_result="${{ needs.pre-merge-pipeline.result }}"
           e2e_tests_pipeline_result="${{ needs.e2e-tests-pipeline.result }}"
+          library_pipeline_result="${{ needs.library-pipeline.result }}"
           detect_changed_folders="${{ needs.detect-changed-folders.outputs.changed_apps }}"
-          echo "E2E test pipeline result: $e2e_tests_pipeline_result"
+
           echo "Pre-merge pipeline result: $pre_merge_pipeline_result"
+          echo "E2E test pipeline result: $e2e_tests_pipeline_result"
+          echo "Library pipeline result: $library_pipeline_result"
           echo "Detect-changed-folders: $detect_changed_folders"
 
-          if [ "$detect_changed_folders" == "[]" ] && [ "$e2e_tests_pipeline_result" == "success" ]; then
-            echo "No project changes found. E2E check passed successfully."
-          elif [ "$pre_merge_pipeline_result" == "success" ]; then
-            echo "pre-merge check passed successfully."
-          else
-            echo "pre-merge check failed or was skipped. PR can't get merged."
+          # E2E tests should always succeed regardless of other changes
+          if [ "$e2e_tests_pipeline_result" != "success" ]; then
+            echo "E2E tests failed. PR can't be merged."
             exit 1
           fi
+
+          # Check library pipeline only if it was required to run (otherwise it will be "skipped")
+          if [ "${{ needs.setup-conditions.outputs.common_condition }}" == "true" ] && [ "$library_pipeline_result" != "success" ]; then
+            echo "Library pipeline check failed. PR can't be merged."
+            exit 1
+          fi
+
+          # Check pre-merge pipeline only if it was required to run
+          has_changes="${{ needs.detect-changed-folders.outputs.changed_apps != '[]' || needs.setup-conditions.outputs.common_condition == 'true' }}"
+          if [ "$has_changes" == "true" ] && [ "$pre_merge_pipeline_result" != "success" ]; then
+            echo "Pre-merge pipeline failed. PR can't be merged."
+            exit 1
+          fi
+
+          echo "All required checks have passed. PR can be merged."
