Added step in library to check if new api changes available

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -2,134 +2,136 @@
 # SPDX-License-Identifier: Apache-2.0
 
 ---
-name: PR Checks
-
-on:
-  pull_request:
-    types: [opened, reopened, synchronize]
-
-jobs:
-  detect-changed-folders:
-    runs-on: 'ubuntu-latest'
-    outputs:
-      changed_projects_root: ${{ steps.discover-changes.outputs.changed_projects }}
-      changed_apps: ${{ steps.discover-changes-apps.outputs.changed_projects }}
-    steps:
-      - name: Git safe directory
-        run: git config --global --add safe.directory $GITHUB_WORKSPACE
-
-      - name: Discover changed folders at root level
-        uses: open-edge-platform/orch-ci/discover-changed-subfolders@main
-        id: discover-changes
-
-      - name: Discover changed apps
-        uses: open-edge-platform/orch-ci/discover-changed-subfolders@main
-        id: discover-changes-apps
-        with:
-          project_folder: "apps"
-
-  license-check:
-    runs-on: 'ubuntu-latest'
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: License check
-        run: make license
-
-  setup-conditions:
-    needs: detect-changed-folders
-    runs-on: 'ubuntu-latest'
-    outputs:
-      common_condition: ${{ contains(needs.detect-changed-folders.outputs.changed_projects_root, 'library') || contains(needs.detect-changed-folders.outputs.changed_projects_root, '.github') || contains(needs.detect-changed-folders.outputs.changed_projects_root, 'common.mk') || '' == 'false' }}
-    steps:
-      - name: Log details
-        run: |
-          echo "Did library or .github dirs change? ${{ contains(needs.detect-changed-folders.outputs.changed_projects_root, 'library') || contains(needs.detect-changed-folders.outputs.changed_projects_root, '.github') || '' == 'false' }}"
-
-  library-pipeline:
-    needs: setup-conditions
-    if: needs.setup-conditions.outputs.common_condition == 'true'
-    uses: ./.github/workflows/library.yml
-
-  e2e-tests-pipeline:
-    uses: ./.github/workflows/e2e-tests.yml
-    secrets: inherit
-
-  pre-merge-pipeline:
-    needs: [detect-changed-folders, setup-conditions]
-    if: needs.setup-conditions.outputs.common_condition == 'false' && fromJson(needs.detect-changed-folders.outputs.changed_apps)[0] != null
-    strategy:
-      fail-fast: false
-      matrix:
-        project_folder: ${{ fromJson(needs.detect-changed-folders.outputs.changed_apps) }}
-    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
-    with:
-      bootstrap_tools: "base,helm,yq,jq"
-      run_security_scans: true
-      run_version_check: true
-      run_dep_version_check: false
-      run_build: true
-      run_lint: true
-      run_test: true
-      run_validate_clean_folder: true
-      run_docker_build: true
-      run_scan_containers: true
-      run_artifact: false
-      run_helm_build: true
-      run_reuse_check: true
-      prefix_tag_separator: "/"
-      project_folder: apps/${{ matrix.project_folder }}
-      orch_ci_repo_ref: main
-    secrets: inherit
-
-  pre-merge-pipeline-all:
-    needs: setup-conditions
-    if: needs.setup-conditions.outputs.common_condition == 'true'
-    strategy:
-      fail-fast: false
-      matrix:
-        project_folder: ["admin", "app-orch", "cluster-orch", "infra", "root"]
-    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
-    with:
-      bootstrap_tools: "base,helm,yq,jq"
-      run_security_scans: true
-      run_version_check: true
-      run_dep_version_check: false
-      run_build: true
-      run_lint: true
-      run_test: true
-      run_validate_clean_folder: true
-      run_docker_build: true
-      run_scan_containers: true
-      run_artifact: false
-      run_helm_build: true
-      run_reuse_check: true
-      prefix_tag_separator: "/"
-      project_folder: apps/${{ matrix.project_folder }}
-      orch_ci_repo_ref: main
-    secrets: inherit
-  final-check:
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: [Detect-changed-folders, pre-merge-pipeline, pre-merge-pipeline-all, e2e-tests-pipeline]
-    steps:
-      - name: Final Status Check
-        run: |
-          pre_merge_pipeline_result="${{ needs.pre-merge-pipeline.result }}"
-          pre_merge_pipeline_result_all="${{ needs.pre-merge-pipeline-all.result }}"
-          e2e_tests_pipeline_result="${{ needs.e2e-tests-pipeline.result }}"
-          detect_changed_folders="${{ needs.detect-changed-folders.outputs.changed_apps }}"
-          echo "E2E test pipeline result: $e2e_tests_pipeline_result"
-          echo "Pre-merge pipeline result: $pre_merge_pipeline_result"
-          echo "Pre-merge pipeline all result: $pre_merge_pipeline_result_all"
-          echo "Detect-changed-folders: $detect_changed_folders"
-
-          if [ "$detect_changed_folders" == "[]" ] && [ "$e2e_tests_pipeline_result" == "success" ]; then
-            echo "No project changes found. E2E check passed successfully."
-          elif [ "$pre_merge_pipeline_result" == "success" ] || [ "$pre_merge_pipeline_result_all" == "success" ]; then
-            echo "At least one pre-merge check passed successfully."
-          else
-            echo "Both pre-merge checks failed or were skipped. PR can't get merged."
-            exit 1
-          fi
+  name: PR Checks
+  
+  on:
+    pull_request:
+      types: [opened, reopened, synchronize]
+  
+  jobs:
+    detect-changed-folders:
+      runs-on: 'ubuntu-latest'
+      outputs:
+        changed_projects_root: ${{ steps.discover-changes.outputs.changed_projects }}
+        changed_apps: ${{ steps.discover-changes-apps.outputs.changed_projects }}
+      steps:
+        - name: Git safe directory
+          run: git config --global --add safe.directory $GITHUB_WORKSPACE
+  
+        - name: Discover changed folders at root level
+          uses: open-edge-platform/orch-ci/discover-changed-subfolders@main
+          id: discover-changes
+  
+        - name: Discover changed apps
+          uses: open-edge-platform/orch-ci/discover-changed-subfolders@main
+          id: discover-changes-apps
+          with:
+            project_folder: "apps"
+  
+    license-check:
+      runs-on: 'ubuntu-latest'
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+  
+        - name: License check
+          run: make license
+  
+    setup-conditions:
+      needs: detect-changed-folders
+      runs-on: 'ubuntu-latest'
+      outputs:
+        common_condition: ${{ contains(needs.detect-changed-folders.outputs.changed_projects_root, 'library') || contains(needs.detect-changed-folders.outputs.changed_projects_root, '.github') || contains(needs.detect-changed-folders.outputs.changed_projects_root, 'common.mk') || '' == 'false' }}
+      steps:
+        - name: Log details
+          run: |
+            echo "Did library or .github dirs change? ${{ contains(needs.detect-changed-folders.outputs.changed_projects_root, 'library') || contains(needs.detect-changed-folders.outputs.changed_projects_root, '.github') || '' == 'false' }}"
+  
+    library-pipeline:
+      needs: setup-conditions
+      if: needs.setup-conditions.outputs.common_condition == 'true'
+      uses: ./.github/workflows/library.yml
+      secrets: inherit
+  
+    e2e-tests-pipeline:
+      uses: ./.github/workflows/e2e-tests.yml
+      secrets: inherit
+  
+    pre-merge-pipeline:
+      needs: [detect-changed-folders, setup-conditions]
+      if: needs.setup-conditions.outputs.common_condition == 'false' && fromJson(needs.detect-changed-folders.outputs.changed_apps)[0] != null
+      strategy:
+        fail-fast: false
+        matrix:
+          project_folder: ${{ fromJson(needs.detect-changed-folders.outputs.changed_apps) }}
+      uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
+      with:
+        bootstrap_tools: "base,helm,yq,jq"
+        run_security_scans: true
+        run_version_check: true
+        run_dep_version_check: false
+        run_build: true
+        run_lint: true
+        run_test: true
+        run_validate_clean_folder: true
+        run_docker_build: true
+        run_scan_containers: true
+        run_artifact: false
+        run_helm_build: true
+        run_reuse_check: true
+        prefix_tag_separator: "/"
+        project_folder: apps/${{ matrix.project_folder }}
+        orch_ci_repo_ref: main
+      secrets: inherit
+  
+    pre-merge-pipeline-all:
+      needs: setup-conditions
+      if: needs.setup-conditions.outputs.common_condition == 'true'
+      strategy:
+        fail-fast: false
+        matrix:
+          project_folder: ["admin", "app-orch", "cluster-orch", "infra", "root"]
+      uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
+      with:
+        bootstrap_tools: "base,helm,yq,jq"
+        run_security_scans: true
+        run_version_check: true
+        run_dep_version_check: false
+        run_build: true
+        run_lint: true
+        run_test: true
+        run_validate_clean_folder: true
+        run_docker_build: true
+        run_scan_containers: true
+        run_artifact: false
+        run_helm_build: true
+        run_reuse_check: true
+        prefix_tag_separator: "/"
+        project_folder: apps/${{ matrix.project_folder }}
+        orch_ci_repo_ref: main
+      secrets: inherit
+    final-check:
+      runs-on: ubuntu-latest
+      if: ${{ always() }}
+      needs: [Detect-changed-folders, pre-merge-pipeline, pre-merge-pipeline-all, e2e-tests-pipeline]
+      steps:
+        - name: Final Status Check
+          run: |
+            pre_merge_pipeline_result="${{ needs.pre-merge-pipeline.result }}"
+            pre_merge_pipeline_result_all="${{ needs.pre-merge-pipeline-all.result }}"
+            e2e_tests_pipeline_result="${{ needs.e2e-tests-pipeline.result }}"
+            detect_changed_folders="${{ needs.detect-changed-folders.outputs.changed_apps }}"
+            echo "E2E test pipeline result: $e2e_tests_pipeline_result"
+            echo "Pre-merge pipeline result: $pre_merge_pipeline_result"
+            echo "Pre-merge pipeline all result: $pre_merge_pipeline_result_all"
+            echo "Detect-changed-folders: $detect_changed_folders"
+  
+            if [ "$detect_changed_folders" == "[]" ] && [ "$e2e_tests_pipeline_result" == "success" ]; then
+              echo "No project changes found. E2E check passed successfully."
+            elif [ "$pre_merge_pipeline_result" == "success" ] || [ "$pre_merge_pipeline_result_all" == "success" ]; then
+              echo "At least one pre-merge check passed successfully."
+            else
+              echo "Both pre-merge checks failed or were skipped. PR can't get merged."
+              exit 1
+            fi
+  
